# Generated by Django 3.2.7 on 2021-12-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='describtion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='listing',
            name='startingBid',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Category'),
        ),
    ]
