# Generated by Django 3.2.7 on 2021-12-20 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211215_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
