# Generated by Django 3.2.7 on 2021-12-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_datecreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='categories',
        ),
    ]
